In [13]:
import jax
import jax.numpy as jnp
from jax.experimental import sparse

# create a sparse matrix
A = jnp.array([[1, 0, 0], [0, 0, 2], [0, 3, 0]])
A = sparse.BCOO.fromdense(A)
print(A.shape)
print(A.indices.shape)

# create a random vector with shape (num_nonzero_elements, 1)
x = jnp.array([[1, 2, 3], [3,4 ,5]]).reshape(2, -1)
batch_idx = jnp.broadcast_to(A.indices, (2, ) + A.indices.shape)
print(x.shape)

B = sparse.BCOO((x, batch_idx), shape=(2,) + A.shape)

(3, 3)
(3, 2)
(2, 3)


In [11]:
# densify the sparse matrix
B = B.todense()

In [12]:
print(B[0])
print(B[1])

[[1 0 0]
 [0 0 2]
 [0 3 0]]
[[3 0 0]
 [0 0 4]
 [0 5 0]]


In [19]:
B @ B.transpose((0, 2, 1))

AttributeError: 'BCOO' object has no attribute 'conj'

In [25]:
import torch
A = torch.arange(5*5)
A = A.reshape(5, 5)
print(A)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


In [30]:
A = torch.arange(5*5)
A = A.reshape(5, 5)
print(A)
B = torch.tensor([[0,0,1,1,1],
                  [0,0,1,0,1],
                  [0,0,1,1,1],
                  [0,0,0,0,0],
                  [0,0,0,0,0]])

A = A[None,...]
B = B[None,...]
print(A.shape)
A = torch.nn.functional.pad(A, (2, 2,2,2), 'circular')
out = torch.nn.functional.conv2d(A, B[None,...], padding='valid')
print(out)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
torch.Size([1, 5, 5])
tensor([[[ 93, 101, 109, 102, 100],
         [ 83,  91,  99,  92,  90],
         [ 48,  56,  64,  57,  55],
         [ 88,  96, 104,  97,  95],
         [128, 136, 144, 137, 135]]])


tensor([[[ 93, 101, 109, 102, 100],
         [ 83,  91,  99,  92,  90],
         [ 48,  56,  64,  57,  55],
         [ 88,  96, 104,  97,  95],
         [128, 136, 144, 137, 135]]])